<%--To avoid the overriding of any manual code changes upon subsequent code generations, disable "Generate JSP Files" option in the Adaptor model.--%>
<!DOCTYPE html>
<%--
 Copyright (c) 2020 KTH Royal Institute of Technology.

 All rights reserved. This program and the accompanying materials
 are made available under the terms of the Eclipse Public License v1.0
 and Eclipse Distribution License v. 1.0 which accompanies this distribution.

 The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 and the Eclipse Distribution License is available at
 http://www.eclipse.org/org/documents/edl-v10.php.

 This file is generated by org.eclipse.lyo.oslc4j.codegenerator
--%>

<%@page import="org.eclipse.lyo.oslc4j.core.OSLC4JUtils"%>
<%@page import="javax.ws.rs.core.UriBuilder"%>
<%@page import="java.net.URI"%>
<%@page import="java.io.File"%>

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<% 
File swaggerFolder = new File(application.getRealPath("/swagger-ui/dist")); 
URI yamlPath = UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path("/swagger.yaml").build();
%>

<html>
<head>
    <meta charset="UTF-8">
    <title>Swagger UI</title>
        <link href="<c:url value="/static/css/bootstrap-4.0.0-beta.min.css"/>" rel="stylesheet">
        <link href="<c:url value="/static/css/adaptor.css"/>" rel="stylesheet">
    
        <script src="<c:url value="/static/js/jquery-3.2.1.min.js"/>"></script>
        <script src="<c:url value="/static/js/bootstrap-4.0.0-beta.min.js"/>"></script>
</head>
<body>
      <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
        <div class="container">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="<c:url value="/"/>"><%= application.getServletContextName() %></a></li>
            <li class="nav-item"><a class="nav-link" href="<c:url value="/services/catalog/singleton"/>">Service Provider Catalog</a></li>
            <li class="nav-item"><a class="nav-link" href="<c:url value="/swagger-ui/index.jsp"/>">Swagger UI</a></li>
          </ul>
        </div>
      </nav>
    
    <div class="container">
        <div class="alert alert-primary" role="alert">
            <h4 class="alert-heading">Swagger UI</h4>
            <hr>
            <p><strong>You don't seem to have enabled Swagger Documentation!</strong></p>
            <ol>
            <li>Generate the necessary code and annotations for Swagger documentation by checking the "Swagger Documentation" option in the Adaptor model.</li>
            <li>Configure your project according to these <a href="<%= "https://wiki.eclipse.org/Lyo/creating_OSLC4J_project#OpenApi.2FSwagger_Support_.28Optional.29" %>">Lyo Instructions for Swagger</a></li>
            </ol>
        </div>
    </div>
    <footer class="footer">
      <div class="container">
        <p class="text-muted">
          OSLC Adaptor was generated using <a href="http://eclipse.org/lyo">Eclipse Lyo</a>.
        </p>
      </div>
    </footer>
</body>
</html>
