apiVersion: v1
kind: Service
metadata:
  name: server-am
  labels:
    app: server-am
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: server-am
