apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-rm-deployment
  labels:
    app: server-rm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-rm
  template:
    metadata:
      labels:
        app: server-rm
    spec:
      containers:
      - name: server-rm
        image: localhost/server-rm:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 384Mi
          requests:
            cpu: 500m
            memory: 384Mi
