apiVersion: v1
kind: Service
metadata:
  name: server-qm
  labels:
    app: server-qm
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: server-qm
