name: Rebase
on:
  schedule:
    - cron:  '40 7 * * *'
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: peter-evans/rebase@e4945786f7ca41fe6e101cead4395f5489593943 #v4.0.0
        with:
          exclude-labels: |
            no-rebase
            dependencies
          # exclude-drafts: true
